export const goodArray = [
  {
    id: 0,
    title: 'Ролл угорь стандарт',
    description: 'Рис, угорь, соус унаги, кунжут, водоросли нори.',
    price: 250,
    type: 'Роллы',
    image: 'good-image-1.jpg',
  },
  {
    id: 1,
    title: 'Калифорния лосось стандарт',
    description: 'Рис, лосось, авокадо, огурец, майонез, икра масаго, водоросли нори.',
    price: 275,
    type: 'Роллы',
    image: 'good-image-2.jpg',
  },
  {
    id: 2,
    title: 'Окинава стандарт',
    description: 'Рис, креветка отварная, сыр сливочный, лосось, огурец свежий...',
    price: 290,
    type: 'Роллы',
    image: 'good-image-3.jpg',
  },
  {
    id: 3,
    title: 'Цезарь маки хl',
    description: 'Рис, куриная грудка копченая, икра масаго, томат, айсберг, соус цезарь...',
    price: 370,
    type: 'Роллы',
    image: 'good-image-4.jpg',
  },
  {
    id: 4,
    title: 'Ясай маки стандарт 185 г',
    description: 'Рис, помидор свежий, перец болгарский, авокадо, огурец, айсберг',
    price: 260,
    type: 'Роллы',
    image: 'good-image-5.jpg',
  },
  {
    id: 5,
    title: 'Ролл с креветкой стандарт',
    description: 'Рис, водоросли нори, креветки отварные, сыр сливочный, огурцы',
    price: 310,
    type: 'Роллы',
    image: 'good-image-6.jpg',
  },
];
