export const restArray = [
  {
    id: 0,
    title: 'Пицца плюс',
    time: 45,
    rating: 4.7,
    price: 910,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-1.jpg',
  },
  {
    id: 1,
    title: 'Тануки',
    time: 37,
    rating: 4.4,
    price: 780,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-2.jpg',
  },
  {
    id: 2,
    title: 'FoodBand',
    time: 55,
    rating: 4.5,
    price: 930,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-3.jpg',
  },
  {
    id: 3,
    title: 'Жадина-пицца',
    time: 51,
    rating: 4.6,
    price: 990,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-4.jpg',
  },
  {
    id: 4,
    title: 'Точка еды',
    time: 43,
    rating: 4.8,
    price: 980,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-5.jpg',
  },
  {
    id: 5,
    title: 'PizzaBurger',
    time: 29,
    rating: 4.1,
    price: 615,
    type: 'Пицца',
    rest: 'Ресторан',
    image: 'image-6.jpg',
  },
];
